# Generated by Django 5.2.5 on 2025-08-21 17:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_blogs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/djyvf2bst/image/upload/v1755795111/profile_image_empkl0.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
